### ISSUE TITLE
code

### ISSUE THREAD

**Issue by lkfiean** [whq-xxh/SFADA-GTV-Seg#1]
代码啥时候发布呢

**Comment by chunyuxiaodao** [comment]
代码啥时候发布呢 @whq-xxh

**Comment by whq-xxh** [comment]
你好，论文还在修改中，接受后发布，感谢关注！
________________________________
发件人: chunyuxiaodao ***@***.***>
发送时间: 2024年5月25日 22:46
收件人: whq-xxh/Active-GTV-Seg ***@***.***>
抄送: Hongqiu WANG ***@***.***>; Mention ***@***.***>
主题: Re: [whq-xxh/Active-GTV-Seg] code (Issue #1)

你通常不会收到来自 ***@***.*** 的电子邮件。了解这一点为什么很重要<https://aka.ms/LearnAboutSenderIdentification>

代码啥时候发布呢 @whq-xxh<https://github.com/whq-xxh>

―

**Comment by whq-xxh** [comment]
Code and data have been uploaded @lkfiean @chunyuxiaodao , email me if you have any questions
